import Footer from "@/components/Footer"
import MobileNavbar from "@/components/MobileNav"
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Prestigelisten - Rangliste over de største cykelryttere',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <MobileNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
